/**
 * Brand HTML template for edition previews — Wadi Bardawil brand system
 * (gunmetal + naranja, Archivo + Manrope; see Brand System DESIGN.md).
 *
 * NEWSLETTER anatomy, not web-page anatomy: centered nameplate (W tile +
 * name + issue line), the issue headline, tight story cards separated by
 * labeled section dividers, and a centered sign-off footer — the Morning
 * Brew / Axios editorial-email pattern adapted to the brand tokens.
 * 600px column (email standard). Ships both brand modes (dark default,
 * light = --wb-light #F4F5F7) with a persisted toggle.
 *
 * Single source of truth for the letter's design. Used by the draft
 * pipeline (src/run.ts) and the drafts re-render script.
 */

export interface EditionHero {
  filename: string;
  altText: string;
  caption: string;
}

export function mdToHtml(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;

  const inline = (s: string) =>
    s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (line.startsWith("# ")) {
      if (inList) { out.push("</ul>"); inList = false; }
      out.push(`<h1>${inline(line.slice(2))}</h1>`);
    } else if (line.startsWith("## ")) {
      if (inList) { out.push("</ul>"); inList = false; }
      out.push(`<h2>${inline(line.slice(3))}</h2>`);
    } else if (line.startsWith("### ")) {
      if (inList) { out.push("</ul>"); inList = false; }
      out.push(`<h3>${inline(line.slice(4))}</h3>`);
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      if (!inList) { out.push("<ul>"); inList = true; }
      out.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (line.startsWith("> ")) {
      if (inList) { out.push("</ul>"); inList = false; }
      out.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);
    } else if (line === "---" || line === "***") {
      if (inList) { out.push("</ul>"); inList = false; }
      out.push("<hr>");
    } else if (line === "") {
      if (inList) { out.push("</ul>"); inList = false; }
    } else {
      if (inList) { out.push("</ul>"); inList = false; }
      out.push(`<p>${inline(line)}</p>`);
    }
  }
  if (inList) out.push("</ul>");
  return out.join("\n");
}

/** Light-mode token overrides (Brand System --wb-light variation pieces). */
const LIGHT_VARS = `--wb-bg: #F4F5F7; --wb-panel: #FFFFFF; --wb-panel-border: rgba(34,40,49,0.09);
    --wb-ink: #222831; --wb-body: #2E3540; --wb-muted: #6B7480; --wb-soft: #454D59;
    --wb-line: rgba(34,40,49,0.16); --wb-folio: #6B7480; color-scheme: light;`;

export function renderEditionHtml(opts: {
  editionId: string;
  title: string;
  markdown: string;
  language: "en" | "es";
  hero?: EditionHero | undefined;
}): string {
  const { editionId, title, markdown, language, hero } = opts;
  const isEs = language === "es";
  // Strip review-only annotations — these are for markdown review only and
  // must not appear in the publish-ready HTML.
  const cleanMd = markdown.replace(/^>[ \t]*⚠️[^\n]*/gm, "").replace(/\n{3,}/g, "\n\n");
  let body = mdToHtml(cleanMd);
  // The markdown h1 is the generic run label; the nameplate replaces it and
  // the issue's subject becomes the headline.
  body = body.replace(/<h1>[\s\S]*?<\/h1>\n?/, "");

  // ── Newsletter anatomy: classify the <hr>-delimited blocks ──────────────
  const blocks = body.split(/<hr>\n?/);
  let metaHtml = "";
  let leadHtml = "";
  let tailNote = "";
  const stories: string[] = [];
  for (const raw of blocks) {
    const block = raw.trim();
    if (!block) continue;
    if (block.includes("<strong>Drafted:</strong>")) {
      // Draft paperwork — demoted to footer fine print.
      metaHtml = block;
      continue;
    }
    if (block.startsWith("<blockquote>") && !block.includes("<h2>")) {
      // Insight summary — the lead callout under the headline.
      leadHtml = `<div class="lead">${block}</div>`;
      continue;
    }
    if (!block.includes("<h2>") && /<em>[\s\S]*<\/em>/.test(block) && block.length < 400) {
      // "Draft generated by the pipeline" note — footer fine print.
      tailNote = block;
      continue;
    }
    stories.push(`<section class="story">\n${block}\n</section>`);
  }

  const draftedDate = /Drafted:<\/strong>\s*([0-9]{4}-[0-9]{2}-[0-9]{2})/.exec(metaHtml)?.[1];
  const issueLabel = isEs ? "Edición" : "Edition";
  const issueLine = [
    `${issueLabel} ${editionId}`,
    language.toUpperCase(),
    ...(draftedDate ? [draftedDate] : []),
  ].join(" · ");

  const toggleLabel = isEs ? "Cambiar tema" : "Toggle theme";
  const nameplate = `<header class="np">
  <button id="wb-theme-toggle" type="button" title="${toggleLabel}" aria-label="${toggleLabel}">◐</button>
  <span class="np-tile">W</span>
  <div class="np-name">The Transformation Letter</div>
  <div class="np-issue">${issueLine}</div>
  <div class="np-bar"></div>
  <h1>${title.replace(/</g, "&lt;")}</h1>
</header>`;

  // Hero image is referenced relatively — both HTML and PNG live in drafts/.
  const heroHtml = hero
    ? `<figure class="hero"><img src="${hero.filename}" alt="${hero.altText.replace(/"/g, "&quot;")}" loading="lazy">${hero.caption ? `<figcaption>${hero.caption.replace(/</g, "&lt;")}</figcaption>` : ""}</figure>`
    : "";

  return `<!DOCTYPE html>
<html lang="${language}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800;900&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<script>
  // Apply the saved theme before first paint to avoid a flash.
  (function () {
    var t = null;
    try { t = localStorage.getItem("wb-theme"); } catch (e) {}
    if (t === "light" || t === "dark") document.documentElement.setAttribute("data-theme", t);
  })();
</script>
<style>
  /* Wadi Bardawil brand system — gunmetal + naranja (Brand System DESIGN.md).
     Dark is the brand default; light is the --wb-light variation. */
  :root {
    --wb-bg: #1A1E25; --wb-panel: #242A34; --wb-panel-border: rgba(255,255,255,0.07);
    --wb-ink: #FFFFFF; --wb-body: #D3D9E1; --wb-muted: #A6AEBA; --wb-soft: #E4E8EE;
    --wb-line: rgba(255,255,255,0.14); --wb-folio: #8A93A0;
    --wb-accent: #FD4002; --wb-accent-press: #D63601;
    color-scheme: dark;
  }
  @media (prefers-color-scheme: light) {
    :root:not([data-theme="dark"]) { ${LIGHT_VARS} }
  }
  :root[data-theme="light"] { ${LIGHT_VARS} }

  * { box-sizing: border-box; }
  body {
    background: var(--wb-bg);
    font-family: Manrope, ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
    width: 100%; max-width: 640px; margin: 0 auto; padding: 28px 14px 40px;
    color: var(--wb-body); line-height: 1.6; font-size: 16.5px;
  }

  /* ── Nameplate — centered email masthead ─────────────────────────────── */
  .np { position: relative; text-align: center; padding: 10px 0 6px; }
  .np-tile {
    display: inline-flex; align-items: center; justify-content: center;
    width: 44px; height: 44px; background: var(--wb-accent); color: #FFFFFF;
    border-radius: 10px; font-family: Archivo, sans-serif; font-weight: 800; font-size: 24px;
    margin-bottom: 12px;
  }
  .np-name {
    font-family: Archivo, Manrope, sans-serif; font-weight: 800;
    font-size: 1.28rem; letter-spacing: 0.14em; text-transform: uppercase;
    color: var(--wb-ink); line-height: 1.2;
  }
  .np-issue {
    font-family: Manrope, sans-serif; font-weight: 600; font-size: 0.76rem;
    letter-spacing: 0.18em; text-transform: uppercase; color: var(--wb-muted);
    margin-top: 6px;
  }
  .np-bar { width: 64px; height: 5px; background: var(--wb-accent); margin: 18px auto; }
  .np h1 {
    font-family: Archivo, Manrope, sans-serif; font-weight: 800;
    color: var(--wb-ink); font-size: 1.75rem; line-height: 1.18;
    letter-spacing: -0.01em; margin: 0 auto 10px; max-width: 32ch; text-wrap: balance;
  }
  #wb-theme-toggle {
    position: absolute; top: 0; right: 0;
    width: 34px; height: 34px; border-radius: 50%;
    background: transparent; border: 1px solid var(--wb-line);
    color: var(--wb-muted); font-size: 16px; line-height: 1; cursor: pointer;
  }
  #wb-theme-toggle:hover { color: var(--wb-accent); border-color: var(--wb-accent); }

  /* ── Lead callout — the issue's thesis, right under the headline ──────── */
  .lead blockquote {
    background: var(--wb-panel); border: 1px solid var(--wb-panel-border);
    border-left: 4px solid var(--wb-accent); border-radius: 0 14px 14px 0;
    margin: 1.2rem 0 1.6rem; padding: 1rem 1.2rem; color: var(--wb-body);
    text-align: left;
  }

  /* ── Story cards — tight blocks with labeled section dividers ─────────── */
  .story {
    background: var(--wb-panel); border: 1px solid var(--wb-panel-border);
    border-radius: 16px; padding: 1.35rem 1.4rem 1.15rem; margin: 1.15rem 0;
  }
  .story h2 {
    display: flex; align-items: center; gap: 14px;
    font-family: Manrope, sans-serif; font-weight: 800;
    font-size: 0.78rem; letter-spacing: 0.26em; text-transform: uppercase;
    color: var(--wb-accent); margin: 0 0 1rem;
  }
  .story h2::before, .story h2::after { content: ""; flex: 1; height: 1px; background: var(--wb-line); }
  .story > p:first-of-type { margin-top: 0; }
  .story > :last-child { margin-bottom: 0.2rem; }

  h3 { font-family: Archivo, Manrope, sans-serif; font-weight: 700; color: var(--wb-ink); font-size: 1.02rem; }
  p { margin: .9rem 0; }
  strong { font-weight: 700; color: var(--wb-ink); }
  em { color: var(--wb-muted); }
  blockquote {
    background: transparent; border-left: 3px solid var(--wb-accent);
    margin: 1.1rem 0; padding: .2rem 0 .2rem 1rem; color: var(--wb-body);
  }
  ul { list-style: none; padding-left: 0; }
  li { margin: .55rem 0; padding-left: 1.3rem; position: relative; color: var(--wb-body); }
  li::before { content: ""; position: absolute; left: 0; top: .52em; width: 8px; height: 8px; background: var(--wb-accent); }
  a { color: var(--wb-ink); text-decoration-color: var(--wb-accent); text-decoration-thickness: 1.5px; text-underline-offset: 3px; }
  a:hover { color: var(--wb-accent); }
  /* External-link affordance — mobile readers have no hover; the arrow says
     the link opens something. Only target=_blank anchors get it. */
  a[target="_blank"]::after { content: " ↗"; font-size: 0.85em; color: var(--wb-accent); }
  img { max-width: 100%; height: auto; border-radius: 12px; }
  .hero { margin: 0 0 1.4rem; text-align: center; }
  .hero figcaption { font-size: 0.88rem; color: var(--wb-muted); margin-top: .5rem; font-style: italic; }

  /* ── Sign-off footer — centered, like an email's closing block ────────── */
  .wb-foot { text-align: center; margin-top: 2.2rem; padding-top: 0.4rem; }
  .wb-foot .np-bar { margin: 16px auto; }
  .foot-lockup {
    display: inline-flex; align-items: center; gap: 10px;
    font-family: Archivo, sans-serif; font-weight: 800; font-size: 12px;
    letter-spacing: 3px; color: var(--wb-ink); text-transform: uppercase;
  }
  .foot-lockup .np-tile { width: 26px; height: 26px; font-size: 14px; border-radius: 6px; margin: 0; }
  .foot-links { margin: 12px 0 4px; font-size: 0.85rem; }
  .foot-links a { color: var(--wb-muted); text-decoration-color: var(--wb-line); margin: 0 8px; }
  .foot-links a:hover { color: var(--wb-accent); }
  .foot-folio {
    font-family: Manrope, sans-serif; font-weight: 600; font-size: 11.5px;
    letter-spacing: 1.5px; text-transform: uppercase; color: var(--wb-folio); margin-top: 8px;
  }
  .foot-fine { border-top: 1px solid var(--wb-line); margin-top: 18px; padding-top: 12px; }
  .foot-fine p { font-size: 0.72rem; color: var(--wb-folio); margin: .2rem 0; }
  .foot-fine strong { color: var(--wb-muted); font-weight: 600; }

  @media (min-width: 480px) {
    body { padding: 36px 24px 48px; }
    .np h1 { font-size: 2rem; }
    .story { padding: 1.5rem 1.7rem 1.3rem; }
  }
  /* Desktop — widen the reading column so the letter doesn't feel like a
     phone view; email-narrow only below tablet. */
  @media (min-width: 900px) {
    body { max-width: 920px; padding: 48px 40px 60px; font-size: 17.5px; }
    .np h1 { font-size: 2.45rem; max-width: 30ch; }
    .story { padding: 2rem 2.6rem 1.7rem; }
    .lead blockquote { padding: 1.3rem 1.7rem; }
  }
</style>
</head>
<body>
${nameplate}
${heroHtml}${leadHtml}
${stories.join("\n")}
<footer class="wb-foot">
  <div class="np-bar"></div>
  <div class="foot-lockup"><span class="np-tile">W</span>Wadi Bardawil</div>
  <div class="foot-links"><a href="https://wadibardawil.com" target="_blank" rel="noopener">wadibardawil.com</a><a href="https://linkedin.com/in/wadibardawil" target="_blank" rel="noopener">LinkedIn</a></div>
  <div class="foot-folio">${issueLine}</div>
  ${metaHtml || tailNote ? `<div class="foot-fine">${metaHtml}${tailNote ? `\n${tailNote}` : ""}</div>` : ""}
</footer>
<script>
  (function () {
    var btn = document.getElementById("wb-theme-toggle");
    if (!btn) return;
    btn.addEventListener("click", function () {
      var root = document.documentElement;
      var current = root.getAttribute("data-theme");
      var next;
      if (current === "light" || current === "dark") {
        next = current === "light" ? "dark" : "light";
      } else {
        var systemLight = window.matchMedia("(prefers-color-scheme: light)").matches;
        next = systemLight ? "dark" : "light";
      }
      root.setAttribute("data-theme", next);
      try { localStorage.setItem("wb-theme", next); } catch (e) {}
    });
  })();
</script>
</body>
</html>`;
}
