/**
 * Phase 2 draft pipeline — CLI entry point.
 *
 * Usage:
 *   pnpm draft
 *   pnpm draft --edition 2026-16
 *
 * Runs: Radar → Strategist → Writer (English) → Validator
 * Saves draft to: drafts/YYYY-WW.md  +  drafts/YYYY-WW-draft.json
 */

import "dotenv/config";
import { randomUUID } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Anthropic from "@anthropic-ai/sdk";
import { AppConfigSchema } from "./types/config.js";
import { createLogger } from "./utils/logger.js";
import { createCostTracker } from "./utils/cost-tracker.js";
import { createApiClients } from "./utils/api-clients.js";
import type { AgentDeps } from "./agents/base-agent.js";
import { RadarAgent } from "./agents/radar.js";
import { StrategistAgent } from "./agents/strategist.js";
import { WriterAgent } from "./agents/writer.js";
import { ValidatorAgent } from "./agents/validator.js";
import type { LocalizedContent, ValidationResult } from "./types/edition.js";
import type { SourceBundle } from "./types/source-bundle.js";
import type { StrategicAngle } from "./types/edition.js";

// ── helpers ──────────────────────────────────────────────────────────────────

function getISOWeek(date: Date): number {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + 4 - (d.getDay() || 7));
  const yearStart = new Date(d.getFullYear(), 0, 1);
  return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
}

function getCurrentEditionId(override?: string): string {
  if (override) return override;
  const now = new Date();
  const year = now.getFullYear();
  const week = String(getISOWeek(now)).padStart(2, "0");
  return `${year}-${week}`;
}

function renderMarkdown(
  editionId: string,
  angle: StrategicAngle,
  content: LocalizedContent,
): string {
  const sections = content.sections;
  const apertura = sections.find((s) => s.type === "lead");
  const insight = sections.find((s) => s.type === "analysis");
  const fieldReport = sections.find((s) => s.type === "spotlight");
  const compass = sections.find((s) => s.type === "quickTakes");
  const door = sections.find((s) => s.type === "cta");

  const now = new Date().toISOString().split("T")[0];

  return [
    `# The Transformation Letter — Edition ${editionId}`,
    ``,
    `**Drafted:** ${now}  `,
    `**OS Pillar:** ${angle.osPillar}  `,
    `**Quarterly Theme:** ${angle.quarterlyTheme}  `,
    `**Subject:** ${content.subject}  `,
    `**Preheader:** ${content.preheader}`,
    ``,
    `---`,
    ``,
    `> **Insight summary:** ${angle.thesis}`,
    ``,
    `---`,
    ``,
    `## THE APERTURA`,
    ``,
    `> ⚠️ WADI REVIEW: Replace this placeholder with your real field observation from this week.`,
    ``,
    apertura?.body ?? "",
    ``,
    `---`,
    ``,
    `## THE INSIGHT`,
    ``,
    insight?.body ?? "",
    ``,
    `---`,
    ``,
    `## THE FIELD REPORT`,
    ``,
    fieldReport?.body ?? "",
    ``,
    `---`,
    ``,
    `## THE COMPASS`,
    ``,
    compass?.body ?? "",
    ``,
    `---`,
    ``,
    `## THE DOOR`,
    ``,
    door?.body ?? "",
    ``,
    `---`,
    ``,
    `*Draft generated by the Writer agent. Review and edit before sending.*`,
  ].join("\n");
}

// ── main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  // Allow --edition YYYY-WW override from CLI args
  const editionArg = process.argv.find((a, i) => process.argv[i - 1] === "--edition");

  const config = AppConfigSchema.parse({
    anthropicApiKey: process.env["ANTHROPIC_API_KEY"],
    beehiivApiKey: process.env["BEEHIIV_API_KEY"],
    beehiivPublicationId: process.env["BEEHIIV_PUBLICATION_ID"],
    feedlyApiKey: process.env["FEEDLY_API_KEY"],
    linkedinAccessToken: process.env["LINKEDIN_ACCESS_TOKEN"],
    twitterApiKey: process.env["TWITTER_API_KEY"],
    twitterApiSecret: process.env["TWITTER_API_SECRET"],
    airtableApiKey: process.env["AIRTABLE_API_KEY"],
    airtableBaseId: process.env["AIRTABLE_BASE_ID"],
    logLevel: process.env["LOG_LEVEL"],
    dryRun: process.env["DRY_RUN"] === "true",
    maxCostPerRunUsd: process.env["MAX_COST_PER_RUN_USD"]
      ? Number(process.env["MAX_COST_PER_RUN_USD"])
      : undefined,
  });

  const logger = createLogger(config.logLevel);
  const costTracker = createCostTracker();
  const apiClients = createApiClients(config);
  const deps: AgentDeps = { logger, costTracker, apiClients };

  const runId = randomUUID();
  const editionId = getCurrentEditionId(editionArg);

  logger.info(`Starting draft pipeline`, { runId, editionId });
  console.log(`\n📰 The Transformation Letter — Draft Pipeline`);
  console.log(`   Run:     ${runId}`);
  console.log(`   Edition: ${editionId}`);
  console.log(`   Time:    ${new Date().toISOString()}\n`);

  // ── Radar ──────────────────────────────────────────────────────────────────
  console.log("🔍 Step 1/3 — Radar: scanning RSS feeds...");
  const radarAgent = new RadarAgent(deps);
  const radarOutput = await radarAgent.run({
    runId,
    editionId,
    agentName: "radar",
    payload: { timeWindowHours: 168, maxItems: 20 },
  });

  if (!radarOutput.success) {
    console.error(`❌ Radar failed: ${radarOutput.error}`);
    process.exit(1);
  }

  const bundle = radarOutput.data as SourceBundle;
  console.log(
    `   ✓ Selected ${bundle.totalSelected} items from ${bundle.metadata.feedsScanned} feeds\n`,
  );

  // ── Strategist ─────────────────────────────────────────────────────────────
  console.log("🧠 Step 2/3 — Strategist: selecting angle...");
  const strategistAgent = new StrategistAgent(deps);
  const strategistOutput = await strategistAgent.run({
    runId,
    editionId,
    agentName: "strategist",
    payload: bundle,
  });

  if (!strategistOutput.success) {
    console.error(`❌ Strategist failed: ${strategistOutput.error}`);
    process.exit(1);
  }

  const angle = strategistOutput.data as StrategicAngle;
  console.log(`   ✓ Angle: "${angle.headline}"`);
  console.log(`   ✓ Pillar: ${angle.osPillar}`);
  console.log(`   ✓ Theme: ${angle.quarterlyTheme}\n`);

  // ── Writer ─────────────────────────────────────────────────────────────────
  console.log("✍️  Step 3/4 — Writer: drafting newsletter...");
  const writerAgent = new WriterAgent(deps);
  const writerOutput = await writerAgent.run({
    runId,
    editionId,
    agentName: "writer",
    payload: {
      angle,
      sources: bundle.items,
      language: "en",
    },
  });

  if (!writerOutput.success) {
    console.error(`❌ Writer failed: ${writerOutput.error}`);
    process.exit(1);
  }

  const content = writerOutput.data as LocalizedContent;
  console.log(`   ✓ Draft complete (${content.sections.length} sections)\n`);

  // ── Validator ──────────────────────────────────────────────────────────────
  console.log("🔎 Step 4/4 — Validator: checking draft against Voice Bible...");
  const validatorAgent = new ValidatorAgent(deps);
  const validatorOutput = await validatorAgent.run({
    runId,
    editionId,
    agentName: "validator",
    payload: { content, angle },
  });

  const validation = validatorOutput.data as ValidationResult | undefined;

  if (!validatorOutput.success || !validation) {
    console.warn(`   ⚠️  Validator failed: ${validatorOutput.error}. Continuing without QA score.\n`);
  } else {
    const icon = validation.isValid ? "✅" : "⚠️ ";
    console.log(`   ${icon} Score: ${validation.score}/100 — ${validation.isValid ? "PASS" : "FAIL"}`);
    const errors = validation.issues.filter((i) => i.severity === "error");
    const warnings = validation.issues.filter((i) => i.severity === "warning");
    if (errors.length > 0) console.log(`   Errors (${errors.length}):`);
    for (const e of errors) console.log(`     • [${e.section}] ${e.message}`);
    if (warnings.length > 0) console.log(`   Warnings (${warnings.length}):`);
    for (const w of warnings.slice(0, 3)) console.log(`     • [${w.section}] ${w.message}`);
    for (const rec of validation.recommendations) console.log(`   → ${rec}`);
    console.log();
  }

  // ── Save draft ─────────────────────────────────────────────────────────────
  const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
  const draftsDir = join(rootDir, "drafts");
  mkdirSync(draftsDir, { recursive: true });

  const mdPath = join(draftsDir, `${editionId}.md`);
  const jsonPath = join(draftsDir, `${editionId}-draft.json`);

  const mdContent = renderMarkdown(editionId, angle, content);
  const validatorCostUsd = validatorOutput.success ? validatorOutput.cost.costUsd : 0;
  const jsonContent = JSON.stringify(
    {
      runId,
      editionId,
      generatedAt: new Date().toISOString(),
      angle,
      content,
      validation: validatorOutput.success ? validation : null,
      costs: {
        radar: radarOutput.cost,
        strategist: strategistOutput.cost,
        writer: writerOutput.cost,
        validator: validatorOutput.cost,
        totalUsd:
          radarOutput.cost.costUsd +
          strategistOutput.cost.costUsd +
          writerOutput.cost.costUsd +
          validatorCostUsd,
      },
    },
    null,
    2,
  );

  writeFileSync(mdPath, mdContent, "utf-8");
  writeFileSync(jsonPath, jsonContent, "utf-8");

  const totalCost =
    radarOutput.cost.costUsd +
    strategistOutput.cost.costUsd +
    writerOutput.cost.costUsd +
    validatorCostUsd;

  console.log(`💾 Draft saved:`);
  console.log(`   ${mdPath}`);
  console.log(`   ${jsonPath}`);
  console.log(`\n💰 Cost breakdown:`);
  console.log(`   Radar:      $${radarOutput.cost.costUsd.toFixed(4)}`);
  console.log(`   Strategist: $${strategistOutput.cost.costUsd.toFixed(4)}`);
  console.log(`   Writer:     $${writerOutput.cost.costUsd.toFixed(4)}`);
  console.log(`   Validator:  $${validatorCostUsd.toFixed(4)}`);
  console.log(`   Total:      $${totalCost.toFixed(4)}`);
  console.log(`\n✅ Done — open ${editionId}.md to review and edit.\n`);
}

main().catch((err) => {
  console.error("Fatal error:", err instanceof Error ? err.message : err);
  process.exit(1);
});
